# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files

datas = []
datas += collect_data_files('kon')


a = Analysis(
    ['run.py'],
    pathex=['src'],
    binaries=[],
    datas=datas,
    hiddenimports=[
        'kon.defaults',
        'kon.sounds',
        'kon.builtin_skills',
        'kon.builtin_skills.init',
        'kon.builtin_skills.review',
        # index (semantic_search, get_repo_skeleton)
        'kon.index',
        'kon.index.manager',
        # lsp (get_diagnostics, go_to_definition)
        'kon.lsp',
        'kon.lsp.client',
        'kon.lsp.manager',
        # mcp bridge
        'kon.mcp',
        # context subsystem
        'kon.context',
        'kon.context.skills',
        'kon.context.project',
        'kon.context.loader',
        'kon.context.git',
        'kon.context.agent_mds',
        'kon.context._xml',
        # core subsystem
        'kon.core',
        'kon.core.types',
        'kon.core.handoff',
        'kon.core.compaction',
        # llm providers
        'kon.llm',
        'kon.llm.base',
        'kon.llm.models',
        'kon.llm.providers',
        'kon.llm.providers.openai_compat',
        'kon.llm.providers.openai_completions',
        'kon.llm.providers.openai_responses',
        'kon.llm.providers.openai_codex_responses',
        'kon.llm.providers.anthropic',
        'kon.llm.providers.anthropic_capabilities',
        'kon.llm.providers.ollama',
        'kon.llm.providers.copilot',
        'kon.llm.providers.copilot_anthropic',
        'kon.llm.providers.github_copilot_headers',
        'kon.llm.providers.azure_ai_foundry',
        'kon.llm.providers.rta',
        'kon.llm.providers.mock',
        'kon.llm.providers.sanitize',
        'kon.llm.oauth',
        'kon.llm.oauth.openai',
        'kon.llm.oauth.copilot',
        # tools (all registered tools)
        'kon.tools',
        'kon.tools.read',
        'kon.tools.edit',
        'kon.tools.write',
        'kon.tools.bash',
        'kon.tools.grep',
        'kon.tools.find',
        'kon.tools.web_search',
        'kon.tools.web_fetch',
        'kon.tools.memory',
        'kon.tools.thinking',
        'kon.tools.arxiv',
        'kon.tools.stackoverflow',
        'kon.tools.github',
        'kon.tools.youtube',
        'kon.tools.lsp',
        'kon.tools.semantic_search',
        'kon.tools.skeleton',
        'kon.tools.refactor',
        'kon.tools.mcp_bridge',
        'kon.tools.base',
        # ui
        'kon.ui',
        'kon.ui.app',
        'kon.ui.widgets',
        'kon.ui.commands',
        'kon.ui.chat',
        'kon.ui.blocks',
        'kon.ui.input',
        'kon.ui.formatting',
        'kon.ui.tool_output',
        'kon.ui.export',
        'kon.ui.clipboard',
        'kon.ui.autocomplete',
        'kon.ui.floating_list',
        'kon.ui.path_complete',
        'kon.ui.tree',
        'kon.ui.session_ui',
        'kon.ui.selection_mode',
        'kon.ui.prompt_history',
        'kon.ui.latex',
        'kon.ui.styles',
        'kon.ui.welcome',
        'kon.ui.app_protocol',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='rta',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
