# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['rta_cli/__init__.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        # Legacy modules
        'rta_cli.functions.get_file_content', 
        'rta_cli.functions.get_files_info', 
        'rta_cli.functions.write_file', 
        'rta_cli.functions.run_command', 
        'rta_cli.functions.grep_search', 
        'rta_cli.functions.glob_search', 
        'rta_cli.functions.edit_file', 
        'rta_cli.functions.edit_file_ast', 
        'rta_cli.functions.apply_diff', 
        'rta_cli.functions.delete_file', 
        'rta_cli.functions.create_dir', 
        'rta_cli.functions.list_directory',
        'rta_cli.functions.semantic_search',
        'rta_cli.functions.get_repo_skeleton',
        'rta_cli.functions.lsp_tools',
        'rta_cli.questions',
        'rta_cli.index.manager',
        'rta_cli.lsp.client',
        'rta_cli.lsp.manager',
        # Modern async core (v0.5.0)
        'rta_cli.main_async',
        'rta_cli.core.provider',
        'rta_cli.core.loop',
        'rta_cli.core.ui',
        'rta_cli.core.tool_manager',
        'rta_cli.core.types',
        'rta_cli.core.events',
        'rta_cli.core.bash_tool',
        'rta_cli.core.edit_tool',
        'rta_cli.core.file_tools',
        'rta_cli.core.lsp_tools',
        'rta_cli.core.mcp_tool',
        'rta_cli.core.tool_base',
        'rta_cli.core.session',
        'rta_cli.core.context',
        'rta_cli.mcp',
        'rta_cli.lsp.client',
        'rta_cli.lsp.manager',
        'rta_cli.functions.lsp_tools',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='rta',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
